"""The ContrAI game-record format.

Public API — consumers write ``from contrai_data import RecordWriter,
load_game, …`` without knowing the internal module layout.
"""

from .exceptions import (
    RecordError,
    RecordFormatError,
    UnsupportedFormatError,
)
from .events import (
    RecordSource,
    SeatKind,
    JoinPhase,
    HandsDerivation,
    RoundOutcome,
    SlamOutcome,
    ScoreSource,
    EndReason,
    Seat,
    ObservedFrom,
    Ruleset,
    SideMark,
    ContractTerms,
    Header,
    GameStarted,
    RoundDealt,
    BidMade,
    CardPlayed,
    BeloteHeld,
    RoundScored,
    GameEnded,
    GameEvent,
)
from .tokens import (
    position_token,
    parse_position,
    side_token,
    parse_side,
    card_token,
    parse_card,
    contract_suit_token,
    parse_contract_suit,
    contract_value_token,
    parse_contract_value,
    bid_payload,
    parse_bid,
    ruleset_payload,
    parse_ruleset,
    parse_timestamp,
)
from .codec import (
    FORMAT,
    FORMAT_FAMILY,
    FORMAT_MAJOR,
    encode,
    decode,
)
from .store import (
    ReadResult,
    RecordWriter,
    read_events,
    records_root,
    games_dir,
    game_path,
    new_game_id,
)
from .projection import (
    RoundRecord,
    GameRecord,
    project,
    load_game,
)

__all__: list[str] = [
    "RecordError",
    "RecordFormatError",
    "UnsupportedFormatError",
    "RecordSource",
    "SeatKind",
    "JoinPhase",
    "HandsDerivation",
    "RoundOutcome",
    "SlamOutcome",
    "ScoreSource",
    "EndReason",
    "Seat",
    "ObservedFrom",
    "Ruleset",
    "SideMark",
    "ContractTerms",
    "Header",
    "GameStarted",
    "RoundDealt",
    "BidMade",
    "CardPlayed",
    "BeloteHeld",
    "RoundScored",
    "GameEnded",
    "GameEvent",
    "position_token",
    "parse_position",
    "side_token",
    "parse_side",
    "card_token",
    "parse_card",
    "contract_suit_token",
    "parse_contract_suit",
    "contract_value_token",
    "parse_contract_value",
    "bid_payload",
    "parse_bid",
    "ruleset_payload",
    "parse_ruleset",
    "parse_timestamp",
    "FORMAT",
    "FORMAT_FAMILY",
    "FORMAT_MAJOR",
    "encode",
    "decode",
    "ReadResult",
    "RecordWriter",
    "read_events",
    "records_root",
    "games_dir",
    "game_path",
    "new_game_id",
    "RoundRecord",
    "GameRecord",
    "project",
    "load_game",
]
